from __future__ import annotations

import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import requests
from sqlalchemy import text

sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.common.db import get_engine
from src.reporting.generate_incident_response_report import build_report


PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = PROJECT_ROOT / "reports" / "latest_incident_response_report.md"

API_URL = os.getenv("API_URL", "http://localhost:8000").rstrip("/")
ALERTMANAGER_URL = os.getenv("ALERTMANAGER_URL", "http://localhost:9093").rstrip("/")

DRILL_ALERT_NAME = os.getenv("DRILL_ALERT_NAME", "JobSkillIncidentDrill")
DRILL_FINGERPRINT = os.getenv(
    "DRILL_FINGERPRINT",
    "jobskill-incident-drill-fingerprint",
)
DRILL_SERVICE = os.getenv("DRILL_SERVICE", "incident-drill")
DRILL_SEVERITY = os.getenv("DRILL_SEVERITY", "warning")
DRILL_INSTANCE = os.getenv("DRILL_INSTANCE", "manual")
DRILL_CREATED_BY = os.getenv("DRILL_CREATED_BY", "incident-drill")

DRILL_CREATE_SILENCE = os.getenv("DRILL_CREATE_SILENCE", "true").lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
DRILL_CLEANUP_BEFORE = os.getenv("DRILL_CLEANUP_BEFORE", "true").lower() in {
    "1",
    "true",
    "yes",
    "y",
    "on",
}
DRILL_SILENCE_DURATION_MINUTES = int(
    os.getenv("DRILL_SILENCE_DURATION_MINUTES", "30")
)


def iso_z(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def get_runbook_url() -> str:
    return f"{API_URL}/runbooks/jobskill_alertmanager_slack_notification.md"


def cleanup_existing_drill_rows() -> None:
    engine = get_engine()

    with engine.begin() as conn:
        conn.execute(
            text(
                """
                DELETE FROM alert_current_states
                WHERE fingerprint = :fingerprint
                   OR alert_name = :alert_name
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
            },
        )

        conn.execute(
            text(
                """
                DELETE FROM alert_acknowledgements
                WHERE fingerprint = :fingerprint
                   OR alert_name = :alert_name
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
            },
        )

        conn.execute(
            text(
                """
                DELETE FROM alert_silence_actions
                WHERE fingerprint = :fingerprint
                   OR alert_name = :alert_name
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
            },
        )

        conn.execute(
            text(
                """
                DELETE FROM alert_events
                WHERE fingerprint = :fingerprint
                   OR alert_name = :alert_name
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
            },
        )


def build_alertmanager_payload(
    status: str,
    starts_at: datetime,
    ends_at: datetime | None,
) -> dict[str, Any]:
    labels = {
        "alertname": DRILL_ALERT_NAME,
        "severity": DRILL_SEVERITY,
        "service": DRILL_SERVICE,
        "instance": DRILL_INSTANCE,
    }

    annotations = {
        "summary": "Incident drill alert",
        "description": (
            "Synthetic alert generated by the incident response drill script."
        ),
        "runbook_url": get_runbook_url(),
        "dashboard_url": "http://localhost:8501",
        "prometheus_url": "http://localhost:9090/alerts",
    }

    return {
        "version": "4",
        "groupKey": f'{{}}:{{alertname="{DRILL_ALERT_NAME}"}}',
        "truncatedAlerts": 0,
        "status": status,
        "receiver": "incident-drill",
        "groupLabels": {
            "alertname": DRILL_ALERT_NAME,
        },
        "commonLabels": labels,
        "commonAnnotations": annotations,
        "externalURL": ALERTMANAGER_URL,
        "alerts": [
            {
                "status": status,
                "labels": labels,
                "annotations": annotations,
                "startsAt": iso_z(starts_at),
                "endsAt": (
                    iso_z(ends_at)
                    if ends_at is not None
                    else "0001-01-01T00:00:00Z"
                ),
                "generatorURL": "http://localhost:9090/graph",
                "fingerprint": DRILL_FINGERPRINT,
            }
        ],
    }


def post_webhook_alert(
    status: str,
    starts_at: datetime,
    ends_at: datetime | None = None,
) -> None:
    payload = build_alertmanager_payload(
        status=status,
        starts_at=starts_at,
        ends_at=ends_at,
    )

    response = requests.post(
        f"{API_URL}/alertmanager/webhook",
        json=payload,
        timeout=10,
    )
    response.raise_for_status()


def create_acknowledgement(ack_at: datetime) -> None:
    engine = get_engine()

    with engine.begin() as conn:
        conn.execute(
            text(
                """
                INSERT INTO alert_acknowledgements (
                    fingerprint,
                    alert_name,
                    severity,
                    service,
                    status,
                    acknowledged_by,
                    note,
                    created_at
                )
                VALUES (
                    :fingerprint,
                    :alert_name,
                    :severity,
                    :service,
                    'firing',
                    :acknowledged_by,
                    :note,
                    :created_at
                )
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
                "severity": DRILL_SEVERITY,
                "service": DRILL_SERVICE,
                "acknowledged_by": DRILL_CREATED_BY,
                "note": (
                    "Incident drill acknowledgement. "
                    "Synthetic alert was reviewed and handled as a demo scenario."
                ),
                "created_at": ack_at.replace(tzinfo=None),
            },
        )


def create_alertmanager_silence(
    starts_at: datetime,
    duration_minutes: int,
) -> str | None:
    ends_at = starts_at + timedelta(minutes=duration_minutes)

    payload = {
        "matchers": [
            {
                "name": "alertname",
                "value": DRILL_ALERT_NAME,
                "isRegex": False,
                "isEqual": True,
            },
            {
                "name": "service",
                "value": DRILL_SERVICE,
                "isRegex": False,
                "isEqual": True,
            },
            {
                "name": "severity",
                "value": DRILL_SEVERITY,
                "isRegex": False,
                "isEqual": True,
            },
        ],
        "startsAt": iso_z(starts_at),
        "endsAt": iso_z(ends_at),
        "createdBy": DRILL_CREATED_BY,
        "comment": "Synthetic silence created by incident response drill.",
    }

    try:
        response = requests.post(
            f"{ALERTMANAGER_URL}/api/v2/silences",
            json=payload,
            timeout=10,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        print(f"[incident-drill][WARN] failed to create Alertmanager silence: {exc}")
        return None

    silence_id = response.json().get("silenceID")

    if not silence_id:
        print("[incident-drill][WARN] silenceID not found in Alertmanager response")
        return None

    return str(silence_id)


def save_silence_action(
    silence_id: str,
    starts_at: datetime,
    duration_minutes: int,
) -> None:
    ends_at = starts_at + timedelta(minutes=duration_minutes)
    engine = get_engine()

    with engine.begin() as conn:
        conn.execute(
            text(
                """
                INSERT INTO alert_silence_actions (
                    silence_id,
                    fingerprint,
                    alert_name,
                    severity,
                    service,
                    instance,
                    action_type,
                    duration_minutes,
                    starts_at,
                    ends_at,
                    created_by,
                    reason
                )
                VALUES (
                    :silence_id,
                    :fingerprint,
                    :alert_name,
                    :severity,
                    :service,
                    :instance,
                    'CREATE',
                    :duration_minutes,
                    :starts_at,
                    :ends_at,
                    :created_by,
                    :reason
                )
                """
            ),
            {
                "silence_id": silence_id,
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
                "severity": DRILL_SEVERITY,
                "service": DRILL_SERVICE,
                "instance": DRILL_INSTANCE,
                "duration_minutes": duration_minutes,
                "starts_at": starts_at.replace(tzinfo=None),
                "ends_at": ends_at.replace(tzinfo=None),
                "created_by": DRILL_CREATED_BY,
                "reason": "Synthetic silence created by incident response drill.",
            },
        )


def write_incident_report() -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    report = build_report()
    REPORT_PATH.write_text(report, encoding="utf-8")


def print_recent_drill_rows() -> None:
    engine = get_engine()

    with engine.begin() as conn:
        rows = conn.execute(
            text(
                """
                SELECT
                    status,
                    alert_name,
                    severity,
                    service,
                    fingerprint,
                    starts_at,
                    ends_at,
                    created_at
                FROM alert_events
                WHERE fingerprint = :fingerprint
                   OR alert_name = :alert_name
                ORDER BY id DESC
                """
            ),
            {
                "fingerprint": DRILL_FINGERPRINT,
                "alert_name": DRILL_ALERT_NAME,
            },
        ).mappings().all()

    print("[incident-drill] alert_events:")
    for row in rows:
        print(dict(row))


def main() -> None:
    now = datetime.now(timezone.utc)

    starts_at = now - timedelta(minutes=15)
    acknowledged_at = now - timedelta(minutes=10)
    silence_started_at = now - timedelta(minutes=9)
    resolved_at = now

    print("[incident-drill] start")
    print(f"[incident-drill] API_URL={API_URL}")
    print(f"[incident-drill] ALERTMANAGER_URL={ALERTMANAGER_URL}")
    print(f"[incident-drill] alert_name={DRILL_ALERT_NAME}")
    print(f"[incident-drill] fingerprint={DRILL_FINGERPRINT}")

    if DRILL_CLEANUP_BEFORE:
        print("[incident-drill] cleanup existing drill rows")
        cleanup_existing_drill_rows()

    print("[incident-drill] post firing alert webhook")
    post_webhook_alert(
        status="firing",
        starts_at=starts_at,
        ends_at=None,
    )

    print("[incident-drill] create acknowledgement")
    create_acknowledgement(ack_at=acknowledged_at)

    if DRILL_CREATE_SILENCE:
        print("[incident-drill] create Alertmanager silence")
        silence_id = create_alertmanager_silence(
            starts_at=silence_started_at,
            duration_minutes=DRILL_SILENCE_DURATION_MINUTES,
        )

        if silence_id:
            print(f"[incident-drill] silence_id={silence_id}")
            save_silence_action(
                silence_id=silence_id,
                starts_at=silence_started_at,
                duration_minutes=DRILL_SILENCE_DURATION_MINUTES,
            )

    print("[incident-drill] post resolved alert webhook")
    post_webhook_alert(
        status="resolved",
        starts_at=starts_at,
        ends_at=resolved_at,
    )

    print("[incident-drill] generate incident response report")
    write_incident_report()

    print_recent_drill_rows()

    print(f"[incident-drill] report={REPORT_PATH}")
    print("[incident-drill] success")


if __name__ == "__main__":
    main()
